name: Compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install X11
        run: sudo apt-get update -y && sudo apt-get install libx11-dev -y

      - name: Export X11 include
        run: export CFLAGS="-I/usr/include/X11"

      - name: Compile project
        run: make
