name: Norm

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  norminette:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install norminette
        run: pip install norminette

      - name: Execute norminette on src
        run: norminette src

      - name: Execute norminette on include
        run: norminette include

      - name: Execute norminette on libft
        run: norminette lib/libft
